name: planogram_validator
description: Aplikasi mobile untuk validasi kepatuhan planogram menggunakan YOLO detections.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # API & HTTP
  http: ^1.1.0
  dio: ^5.3.0
  
  # State Management
  provider: ^6.0.0
  
  # JSON serialization
  json_serializable: ^6.7.0
  json_annotation: ^4.11.0
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  
  # Charts & Data Visualization
  fl_chart: ^0.65.0
  
  # File picking & image selection
  image_picker: ^1.0.0
  file_picker: ^8.1.7
  
  # Image processing
  image: ^4.0.0

  # Formatting & utilities
  intl: ^0.19.0
  uuid: ^4.0.0
  
  # Logging
  logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       # - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
